# fly.toml app configuration file generated for jogodefut on 2026-05-10T03:39:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jogodefut'
primary_region = 'gru'

[build]

[processes]
  app = "gunicorn --workers 1 --threads 4 --timeout 120 app:app"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
